{{- if .Values.global.host -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "mesh-operator.fullname" . }}
  labels:
    {{- include "mesh-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "mesh-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "mesh-operator.serviceAccountName" . }}
    namespace: {{ include "mesh-operator.namespace" . }}
{{- end }}
