{{- if .Values.global.host -}}
{{- if .Values.issuer.selfsigned.enabled -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: istio-selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-cacert
  namespace: {{ .Values.issuer.selfsigned.certificateNamespace }}
spec:
  secretName: istio-cacert
  duration: {{ .Values.issuer.selfsigned.duration }}
  renewBefore: {{ .Values.issuer.selfsigned.renewBefore }}
  subject:
    organizations:
      - Istio
  commonName: Root CA
  isCA: true
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  issuerRef:
    name: istio-selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: istio-ca-issuer
spec:
  ca:
    secretName: istio-cacert
{{- end }}
{{- end }}

