{{- if .Values.global.host -}}
{{- if .Values.psp.create -}}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "mesh-operator.fullname" . }}
  labels:
    {{- include "mesh-operator.labels" . | nindent 4 }}
spec:
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  readOnlyRootFilesystem: true
  volumes:
    - secret
{{- end }}
{{- end }}
