{{- if .Values.global.host -}}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mesh-operator.serviceAccountName" . }}
  namespace: {{ include "mesh-operator.namespace" . }}
  labels:
    {{- include "mesh-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
