{{- if .Values.global.host -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mesh-api.fullname" . }}
  namespace: {{ include "mesh-api.namespace" . }}
  labels:
    name: {{ include "mesh-api.fullname" . }}
    system/svcName: {{ include "mesh-api.fullname" . }}
    system/appName: mesh-services
    {{- include "mesh-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 28080
      protocol: TCP
      name: http-{{ include "mesh-api.fullname" . }}
  selector:
    {{- include "mesh-api.selectorLabels" . | nindent 4 }}
{{- end }}
