{{- if .Values.global.host -}}
{{- if .Values.psp.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "tdsf-portal.fullname" . }}-psp-rolebinding
  namespace: {{ include "tdsf-portal.namespace" . }}
  labels:
    {{- include "tdsf-portal.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "tdsf-portal.fullname" . }}-psp-role
subjects:
- kind: ServiceAccount
  name: {{ include "tdsf-portal.serviceAccountName" . }}
  namespace: {{ include "tdsf-portal.namespace" . }}
{{- end }}
{{- end }}
