{{- if .Values.global.host -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tdsf-portal.fullname" . }}
  namespace: {{ include "tdsf-portal.namespace" . }}
  labels:
    {{- include "tdsf-portal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8989
      protocol: TCP
      name: http
  selector:
    {{- include "tdsf-portal.selectorLabels" . | nindent 4 }}
{{- end }}
