{{- if .Values.global.host -}}
apiVersion: component.t7d.io/v1beta1
kind: Component
metadata:
  name: tdsf
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
spec:
  application:
    helmChart:
      name: tdsf-helm-chart
      valuesConfig: values.yaml of tdsf helm chart
      version: v5.6.0
    name: tdsf
  menu:
    name: tdsf-root-menu
  portal:
    entry: /tdsf-public/public/index.html
    path: /service-mesh-management
{{- end }}