{{- if .Values.psp.create -}}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ include "registry-adaptor.fullname" . }}
  labels:
    {{- include "registry-adaptor.labels" . | nindent 4 }}
spec:
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
  - ALL
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  readOnlyRootFilesystem: true
  volumes:
  - secret
  - emptyDir
{{- end }}
