apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "registry-adaptor.fullname" . }}-leader-election-role
  namespace: {{ include "registry-adaptor.namespace" . }}
  labels:
    {{- include "registry-adaptor.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
{{- if .Values.psp.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "registry-adaptor.fullname" . }}-psp-role
  namespace: {{ include "registry-adaptor.namespace" . }}
  labels:
    {{- include "registry-adaptor.labels" . | nindent 4 }}
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  resourceNames:
  - {{ include "registry-adaptor.fullname" . }}
  verbs:
  - use
{{- end }}
