apiVersion: v1
kind: Service
metadata:
  name: {{ include "registry-adaptor.fullname" . }}-metrics-service
  namespace: {{ include "registry-adaptor.namespace" . }}
  labels:
    {{- include "registry-adaptor.labels" . | nindent 4 }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    {{- include "registry-adaptor.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "registry-adaptor.fullname" . }}-webhook-service
  namespace: {{ include "registry-adaptor.namespace" . }}
  labels:
    {{- include "registry-adaptor.labels" . | nindent 4 }}
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    {{- include "registry-adaptor.selectorLabels" . | nindent 4 }}