{{- $cn := printf "%s-webhook-service.%s" (include "registry-adaptor.fullname" .) (include "registry-adaptor.namespace" .) }}
{{- $ips := (list "127.0.0.1") -}}
{{- $names := (list "localhost" $cn (printf "%s" $cn) (printf "%s.svc" $cn) (printf "%s.svc.cluster.local" $cn) ) -}}
{{- $ca := genCA "TDSF" 36500 -}}
{{- $cert := genSignedCert $cn $ips $names 36500 $ca -}}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "registry-adaptor.fullname" . }}-validating-webhook-configuration
  labels:
    {{- include "registry-adaptor.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: {{ b64enc $ca.Cert }}
    service:
      name: {{ include "registry-adaptor.fullname" . }}-webhook-service
      namespace: {{ include "registry-adaptor.namespace" . }}
      path: /validate-mesh-t7d-io-v1-meshservice
  failurePolicy: Fail
  name: vmeshservice.kb.io
  rules:
  - apiGroups:
    - mesh.t7d.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - meshservices
  sideEffects: None
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "registry-adaptor.fullname" . }}-webhook-server-cert
  namespace: {{ include "registry-adaptor.namespace" . }}
  labels:
    {{- include "registry-adaptor.labels" . | nindent 4 }}
data:
  tls.crt: {{ b64enc $cert.Cert }}
  tls.key: {{ b64enc $cert.Key }}
type: kubernetes.io/tls